// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TripTracker.Services.TravelGroupApi.Data;

#nullable disable

namespace TripTracker.Services.TravelGroupApi.Migrations
{
    [DbContext(typeof(TravelGroupDbContext))]
    [Migration("20250506194258_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TripTracker.Services.TravelGroupApi.Models.TravelGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("CreatedDate")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MemberCount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Place")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TravelGroups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateOnly(2025, 5, 6),
                            Description = "Friends from palur and varanasi.",
                            MemberCount = 0,
                            Name = "Friends Group",
                            Place = "Keelapalur/Varanasi"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateOnly(2025, 5, 6),
                            Description = "Friends from Aeronautical education.",
                            MemberCount = 0,
                            Name = "Aero Group",
                            Place = "Chennai"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
