// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TripTracker.Services.TripApi.Data;

#nullable disable

namespace TripTracker.Services.TripApi.Migrations
{
    [DbContext(typeof(TripDbContext))]
    partial class TripDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TripTracker.Services.TripApi.Models.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedByUserEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.PrimitiveCollection<string>("ExpenseIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("ParticipantIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TotalExpense")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("TravelGroupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Trips");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A relaxing summer retreat in the hills of Ooty.",
                            EndDate = new DateOnly(2025, 5, 20),
                            ExpenseIds = "[]",
                            From = "Keelapalur",
                            Name = "Ooty Summer Escape",
                            Notes = "Wonderful weather, visited the Botanical Gardens and tea estates.",
                            ParticipantIds = "[]",
                            StartDate = new DateOnly(2025, 5, 15),
                            Status = "Completed",
                            To = "Ooty",
                            TotalExpense = 25000m,
                            TravelGroupId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Exploring the lakes and forests of Kodaikanal.",
                            EndDate = new DateOnly(2025, 6, 14),
                            ExpenseIds = "[]",
                            From = "Keelapalur",
                            Name = "Kodaikanal Adventure",
                            Notes = "Looking forward to trekking and boating.",
                            ParticipantIds = "[]",
                            StartDate = new DateOnly(2025, 6, 10),
                            Status = "Planned",
                            To = "Kodaikanal",
                            TotalExpense = 18000m,
                            TravelGroupId = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "A cultural trip to explore the royal city of Mysore.",
                            EndDate = new DateOnly(2025, 4, 7),
                            ExpenseIds = "[]",
                            From = "Keelapalur",
                            Name = "Mysore Cultural Tour",
                            Notes = "Visited Mysore Palace and Brindavan Gardens.",
                            ParticipantIds = "[]",
                            StartDate = new DateOnly(2025, 4, 5),
                            Status = "Completed",
                            To = "Mysore",
                            TotalExpense = 15000m,
                            TravelGroupId = 3
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
